name: .NET

on:
  push:
    branches: 
    - main
    - 'releases/**'
  pull_request:
    branches: 
    - main
    - 'releases/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      continue-on-error: true
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push "**\*.nupkg" -k $env:NUGET_API_KEY -s https://api.nuget.org/v3/index.json